### ISSUE TITLE
Uniswap - AnteUniswapLiquidityTVLTest - 

### ISSUE THREAD

**Issue by danielcrt** [antefinance/ante-community-tests#148]
I think there is a mistaked on this line: 
https://github.com/antefinance/ante-community-tests/blob/578f9a47d69f2d9dbb4121f0f53d19d192918dd3/contracts/uniswap/AnteUniswapLiquidityTVLTest.sol#L53

I think the intended check was:
```return (ethusdcDollarValue / ethusdtDollarValue <= 10);```

**Comment by delalunia** [comment]
Yeah, I believe you're right, otherwise it's always 1 and true 😄

**Comment by delalunia** [comment]
Fixed!
