### ISSUE TITLE
Test fails if preCheck fails due to a flash loan attach

### ISSUE THREAD

**Issue by danielcrt** [antefinance/ante-community-tests#97]
https://github.com/antefinance/ante-community-tests/blob/e85d52c12fd58841253d5096dc12ef03405ff1dc/contracts/Convex/AntecvxCRVPegTest.sol#L55

Can be replaced with an OR condition
`if ((slip < 105 && slip > 95) || (preCheckSlip < 105 && preCheckSlip > 95))`

**Comment by delalunia** [comment]
This test is no longer valid due to these not being pegged anymore
